/**
 * Env file writer
 *
 * Writes .env files to scripts/bootstrap/output/<projectName>/
 * so you can copy them into your cloned repo.
 */

import { mkdirSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_DIR = path.resolve(__dirname, "../output");

/**
 * @param {object} opts
 * @param {string} opts.projectName
 * @param {string} opts.databaseUrl     - Pooled (pgBouncer) connection
 * @param {string} [opts.directUrl]     - Direct (non-pooled) connection — required by Prisma CLI for migrations. Falls back to databaseUrl if omitted.
 * @param {"aws"|"vercel"} opts.hosting
 * @param {string} opts.nextAuthSecret  - Pre-generated secret (same value used for Vercel + GitHub secrets)
 * @param {string} opts.privateKey      - Pre-generated NEXT_PUBLIC_PRIVATE_KEY
 */
export async function writeEnvFiles({ projectName, databaseUrl, directUrl, hosting, nextAuthSecret, privateKey }) {
  const dir = path.join(OUTPUT_DIR, projectName);
  mkdirSync(dir, { recursive: true });

  // Secrets are passed in so all env files, Vercel projects, and GitHub
  // Actions secrets share the same values (not independently generated).
  const direct  = directUrl ?? databaseUrl;
  const appUrl  = hosting === "vercel" ? `https://${projectName}.vercel.app`            : "http://YOUR_EC2_IP:3000";
  const dashUrl = hosting === "vercel" ? `https://${projectName}-dashboard.vercel.app`  : "http://YOUR_EC2_IP:3001";

  // Root .env (used at build time by Prisma + the with-root-env wrapper).
  // TT-118: DIRECT_URL is needed for `prisma migrate deploy` during builds.
  // NEXT_PUBLIC_APP_URL feeds @repo/env's marketingAppUrl() helper that
  // builds password-reset links — must be set or links go to example.com.
  const rootEnv = `# Generated by turbo-temp bootstrap
# Copy this file to your project root as .env

DATABASE_URL="${databaseUrl}"
DIRECT_URL="${direct}"

NEXTAUTH_SECRET="${nextAuthSecret}"
NEXT_PUBLIC_APP_URL="${appUrl}"

# OAuth providers (TT-118) — sign-in pages gate buttons on env-var presence.
# Leave blank to disable that provider.
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
GITHUB_CLIENT_ID=""
GITHUB_CLIENT_SECRET=""

# Resend (TT-118) — required in prod for password-reset emails.
# Dev falls back to console-logging when RESEND_API_KEY is unset.
RESEND_API_KEY=""
RESEND_FROM_EMAIL="noreply@example.com"
`;

  // apps/app .env.local — usually only needs NEXTAUTH_URL override locally;
  // most vars come from root .env via the with-root-env wrapper.
  const appEnv = `# Generated by turbo-temp bootstrap
# Copy to apps/app/.env.local

NEXTAUTH_URL="${appUrl}"

NEXT_PUBLIC_PRIVATE_KEY="${privateKey}"
NEXT_PUBLIC_BACKEND_URL="${hosting === "vercel" ? `https://${projectName}-api.vercel.app/graphql` : "http://YOUR_EC2_IP:4000/graphql"}"
`;

  // apps/dashboard .env.local
  const dashEnv = `# Generated by turbo-temp bootstrap
# Copy to apps/dashboard/.env.local

NEXTAUTH_URL="${dashUrl}"

NEXT_PUBLIC_PRIVATE_KEY="${privateKey}"
NEXT_PUBLIC_BACKEND_URL="${hosting === "vercel" ? `https://${projectName}-api.vercel.app/graphql` : "http://YOUR_EC2_IP:4000/graphql"}"
`;

  writeFileSync(path.join(dir, ".env"), rootEnv);
  writeFileSync(path.join(dir, "app.env.local"), appEnv);
  writeFileSync(path.join(dir, "dashboard.env.local"), dashEnv);

  // Also write a README with copy instructions
  const readme = `# ${projectName} — env files

Generated by turbo-temp bootstrap on ${new Date().toISOString().split("T")[0]}.

## Copy instructions

\`\`\`sh
cp .env           ../../.env
cp app.env.local  ../../apps/app/.env.local
cp dashboard.env.local ../../apps/dashboard/.env.local
\`\`\`

Then fill in any missing values (Google OAuth, etc.) before running \`pnpm dev\`.
`;

  writeFileSync(path.join(dir, "README.md"), readme);
}

